# This workflow will do a clean install of node dependencies,
# build the source code and run tests across different version of node
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Mon Service - CI
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: debian-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node_version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Build Project
        run: pnpm run build --if-present
      - name: Launch tests
        run: pnpm run test
